// Generated by CoffeeScript 1.10.0
(function() {
  var loadSampleText;

  $(function() {
    return loadSampleText();
  });

  loadSampleText = function() {
    return $.ajax({
      url: "sampleEditorText.txt",
      dataType: "text",
      success: function(data) {
        return $("#editor-text").text(data);
      }
    });
  };

}).call(this);

//# sourceMappingURL=editor.js.map
